name: Issues Trigger Workflow
on: issues
jobs:
    issue-event:
        runs-on: ubuntu-latest
        steps:
            - name: Output the Issue Event details
              run: echo "${{toJSON(github.event)}}"
