name: Lint test Deploy
on: [issues]
jobs:
    issue-event:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: Output the Issue Event
              run: echo ${{toJSON(github.event)}}
