name: Lint test Deploy
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: download Code
              run: actions/checkout@v3
            - name: lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: download Code
              run: actions/checkout@v3
            - name: testing
              run: npm run test
    deploy:
        runs-on: ubuntu-latest
        needs: [lint,test]
        steps:
            - name: download Code
              run: actions/checkout@v3
            - name: testing
              run: npm run test
    
